Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "GroupTapExpressionGraph" line 1, position 14
Keyword "extends" line 1, position 38
Identifier "ExpressionGraph" line 1, position 46
Separator "{" line 1, position 62
Modifier "public" line 1, position 64
Identifier "GroupTapExpressionGraph" line 1, position 71
Separator "(" line 1, position 94
Separator ")" line 1, position 95
Separator "{" line 1, position 97
Keyword "super" line 1, position 99
Separator "(" line 1, position 104
Identifier "SearchOrder" line 1, position 106
Separator "." line 1, position 117
Identifier "ReverseTopological" line 1, position 118
Separator ")" line 1, position 137
Separator ";" line 1, position 138
Keyword "this" line 1, position 140
Separator "." line 1, position 145
Identifier "arc" line 1, position 146
Separator "(" line 1, position 149
Keyword "new" line 1, position 151
Identifier "FlowElementExpression" line 1, position 155
Separator "(" line 1, position 176
Identifier "Group" line 1, position 178
Separator "." line 1, position 183
Keyword "class" line 1, position 184
Separator ")" line 1, position 190
Separator "," line 1, position 191
Identifier "ScopeExpression" line 1, position 193
Separator "." line 1, position 208
Identifier "ALL" line 1, position 209
Separator "," line 1, position 212
Keyword "new" line 1, position 214
Identifier "FlowElementExpression" line 1, position 218
Separator "(" line 1, position 239
Identifier "ElementCapture" line 1, position 241
Separator "." line 1, position 255
Identifier "Primary" line 1, position 256
Separator "," line 1, position 263
Identifier "Tap" line 1, position 265
Separator "." line 1, position 268
Keyword "class" line 1, position 269
Separator ")" line 1, position 275
Separator ")" line 1, position 277
Separator ";" line 1, position 278
Separator "}" line 1, position 280
Separator "}" line 1, position 282
