Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "NotElementExpression" line 1, position 14
Keyword "extends" line 1, position 35
Identifier "ElementExpression" line 1, position 43
Separator "{" line 1, position 61
Modifier "public" line 1, position 63
Modifier "static" line 1, position 70
Identifier "ElementExpression" line 1, position 77
Identifier "not" line 1, position 95
Separator "(" line 1, position 98
Identifier "ElementExpression" line 1, position 100
Identifier "elementMatcher" line 1, position 118
Separator ")" line 1, position 133
Separator "{" line 1, position 135
Keyword "return" line 1, position 137
Keyword "new" line 1, position 144
Identifier "NotElementExpression" line 1, position 148
Separator "(" line 1, position 168
Identifier "elementMatcher" line 1, position 170
Separator ")" line 1, position 185
Separator ";" line 1, position 186
Separator "}" line 1, position 188
Identifier "ElementExpression" line 1, position 190
Identifier "delegate" line 1, position 208
Separator ";" line 1, position 216
Modifier "public" line 1, position 218
Identifier "NotElementExpression" line 1, position 225
Separator "(" line 1, position 245
Identifier "ElementExpression" line 1, position 247
Identifier "delegate" line 1, position 265
Separator ")" line 1, position 274
Separator "{" line 1, position 276
Keyword "this" line 1, position 278
Separator "." line 1, position 282
Identifier "delegate" line 1, position 283
Operator "=" line 1, position 292
Identifier "delegate" line 1, position 294
Separator ";" line 1, position 302
Separator "}" line 1, position 304
Annotation "@" line 1, position 306
Identifier "Override" line 1, position 307
Modifier "public" line 1, position 316
BasicType "boolean" line 1, position 323
Identifier "applies" line 1, position 331
Separator "(" line 1, position 338
Identifier "PlannerContext" line 1, position 340
Identifier "plannerContext" line 1, position 355
Separator "," line 1, position 369
Identifier "ElementGraph" line 1, position 371
Identifier "elementGraph" line 1, position 384
Separator "," line 1, position 396
Identifier "FlowElement" line 1, position 398
Identifier "flowElement" line 1, position 410
Separator ")" line 1, position 422
Separator "{" line 1, position 424
Keyword "return" line 1, position 426
Operator "!" line 1, position 433
Identifier "delegate" line 1, position 434
Separator "." line 1, position 442
Identifier "applies" line 1, position 443
Separator "(" line 1, position 450
Identifier "plannerContext" line 1, position 452
Separator "," line 1, position 466
Identifier "elementGraph" line 1, position 468
Separator "," line 1, position 480
Identifier "flowElement" line 1, position 482
Separator ")" line 1, position 494
Separator ";" line 1, position 495
Separator "}" line 1, position 497
Annotation "@" line 1, position 499
Identifier "Override" line 1, position 500
Modifier "public" line 1, position 509
Identifier "ElementCapture" line 1, position 516
Identifier "getCapture" line 1, position 531
Separator "(" line 1, position 541
Separator ")" line 1, position 542
Separator "{" line 1, position 544
Keyword "return" line 1, position 546
Identifier "delegate" line 1, position 553
Separator "." line 1, position 561
Identifier "getCapture" line 1, position 562
Separator "(" line 1, position 572
Separator ")" line 1, position 573
Separator ";" line 1, position 574
Separator "}" line 1, position 576
Annotation "@" line 1, position 578
Identifier "Override" line 1, position 579
Modifier "public" line 1, position 588
Identifier "String" line 1, position 595
Identifier "toString" line 1, position 602
Separator "(" line 1, position 610
Separator ")" line 1, position 611
Separator "{" line 1, position 613
Modifier "final" line 1, position 615
Identifier "StringBuilder" line 1, position 621
Identifier "sb" line 1, position 635
Operator "=" line 1, position 638
Keyword "new" line 1, position 640
Identifier "StringBuilder" line 1, position 644
Separator "(" line 1, position 657
String ""Not{"" line 1, position 659
Separator ")" line 1, position 666
Separator ";" line 1, position 667
Identifier "sb" line 1, position 669
Separator "." line 1, position 671
Identifier "append" line 1, position 672
Separator "(" line 1, position 678
Identifier "delegate" line 1, position 680
Separator ")" line 1, position 689
Separator ";" line 1, position 690
Identifier "sb" line 1, position 692
Separator "." line 1, position 694
Identifier "append" line 1, position 695
Separator "(" line 1, position 701
String "'}'" line 1, position 703
Separator ")" line 1, position 707
Separator ";" line 1, position 708
Keyword "return" line 1, position 710
Identifier "sb" line 1, position 717
Separator "." line 1, position 719
Identifier "toString" line 1, position 720
Separator "(" line 1, position 728
Separator ")" line 1, position 729
Separator ";" line 1, position 730
Separator "}" line 1, position 732
Separator "}" line 1, position 734
