Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "ClassRequest" line 1, position 14
Keyword "extends" line 1, position 27
Identifier "MemoizingRequest" line 1, position 35
Separator "{" line 1, position 52
Modifier "private" line 1, position 54
Modifier "final" line 1, position 62
Identifier "Class" line 1, position 68
Operator "<" line 1, position 73
Operator "?" line 1, position 74
Operator ">" line 1, position 75
Identifier "fTestClass" line 1, position 77
Separator ";" line 1, position 87
Modifier "private" line 1, position 89
Modifier "final" line 1, position 97
BasicType "boolean" line 1, position 103
Identifier "canUseSuiteMethod" line 1, position 111
Separator ";" line 1, position 128
Modifier "public" line 1, position 130
Identifier "ClassRequest" line 1, position 137
Separator "(" line 1, position 149
Identifier "Class" line 1, position 150
Operator "<" line 1, position 155
Operator "?" line 1, position 156
Operator ">" line 1, position 157
Identifier "testClass" line 1, position 159
Separator "," line 1, position 168
BasicType "boolean" line 1, position 170
Identifier "canUseSuiteMethod" line 1, position 178
Separator ")" line 1, position 195
Separator "{" line 1, position 197
Keyword "this" line 1, position 199
Separator "." line 1, position 203
Identifier "fTestClass" line 1, position 204
Operator "=" line 1, position 215
Identifier "testClass" line 1, position 217
Separator ";" line 1, position 226
Keyword "this" line 1, position 228
Separator "." line 1, position 232
Identifier "canUseSuiteMethod" line 1, position 233
Operator "=" line 1, position 251
Identifier "canUseSuiteMethod" line 1, position 253
Separator ";" line 1, position 270
Separator "}" line 1, position 272
Modifier "public" line 1, position 274
Identifier "ClassRequest" line 1, position 281
Separator "(" line 1, position 293
Identifier "Class" line 1, position 294
Operator "<" line 1, position 299
Operator "?" line 1, position 300
Operator ">" line 1, position 301
Identifier "testClass" line 1, position 303
Separator ")" line 1, position 312
Separator "{" line 1, position 314
Keyword "this" line 1, position 316
Separator "(" line 1, position 320
Identifier "testClass" line 1, position 321
Separator "," line 1, position 330
Boolean "true" line 1, position 332
Separator ")" line 1, position 336
Separator ";" line 1, position 337
Separator "}" line 1, position 339
Annotation "@" line 1, position 341
Identifier "Override" line 1, position 342
Modifier "protected" line 1, position 351
Identifier "Runner" line 1, position 361
Identifier "createRunner" line 1, position 368
Separator "(" line 1, position 380
Separator ")" line 1, position 381
Separator "{" line 1, position 383
Keyword "return" line 1, position 385
Keyword "new" line 1, position 392
Identifier "CustomAllDefaultPossibilitiesBuilder" line 1, position 396
Separator "(" line 1, position 432
Separator ")" line 1, position 433
Separator "." line 1, position 434
Identifier "safeRunnerForClass" line 1, position 435
Separator "(" line 1, position 453
Identifier "fTestClass" line 1, position 454
Separator ")" line 1, position 464
Separator ";" line 1, position 465
Separator "}" line 1, position 467
Modifier "private" line 1, position 469
Keyword "class" line 1, position 477
Identifier "CustomAllDefaultPossibilitiesBuilder" line 1, position 483
Keyword "extends" line 1, position 520
Identifier "AllDefaultPossibilitiesBuilder" line 1, position 528
Separator "{" line 1, position 559
Annotation "@" line 1, position 561
Identifier "Override" line 1, position 562
Modifier "protected" line 1, position 571
Identifier "RunnerBuilder" line 1, position 581
Identifier "suiteMethodBuilder" line 1, position 595
Separator "(" line 1, position 613
Separator ")" line 1, position 614
Separator "{" line 1, position 616
Keyword "return" line 1, position 618
Keyword "new" line 1, position 625
Identifier "CustomSuiteMethodBuilder" line 1, position 629
Separator "(" line 1, position 653
Separator ")" line 1, position 654
Separator ";" line 1, position 655
Separator "}" line 1, position 657
Separator "}" line 1, position 659
Modifier "private" line 1, position 661
Keyword "class" line 1, position 669
Identifier "CustomSuiteMethodBuilder" line 1, position 675
Keyword "extends" line 1, position 700
Identifier "SuiteMethodBuilder" line 1, position 708
Separator "{" line 1, position 727
Annotation "@" line 1, position 729
Identifier "Override" line 1, position 730
Modifier "public" line 1, position 739
Identifier "Runner" line 1, position 746
Identifier "runnerForClass" line 1, position 753
Separator "(" line 1, position 767
Identifier "Class" line 1, position 768
Operator "<" line 1, position 773
Operator "?" line 1, position 774
Operator ">" line 1, position 775
Identifier "testClass" line 1, position 777
Separator ")" line 1, position 786
Keyword "throws" line 1, position 788
Identifier "Throwable" line 1, position 795
Separator "{" line 1, position 805
Keyword "if" line 1, position 807
Separator "(" line 1, position 810
Identifier "testClass" line 1, position 811
Operator "==" line 1, position 821
Identifier "fTestClass" line 1, position 824
Operator "&&" line 1, position 835
Operator "!" line 1, position 838
Identifier "canUseSuiteMethod" line 1, position 839
Separator ")" line 1, position 856
Separator "{" line 1, position 858
Keyword "return" line 1, position 860
Null "null" line 1, position 867
Separator ";" line 1, position 871
Separator "}" line 1, position 873
Keyword "return" line 1, position 875
Keyword "super" line 1, position 882
Separator "." line 1, position 887
Identifier "runnerForClass" line 1, position 888
Separator "(" line 1, position 902
Identifier "testClass" line 1, position 903
Separator ")" line 1, position 912
Separator ";" line 1, position 913
Separator "}" line 1, position 915
Separator "}" line 1, position 917
Separator "}" line 1, position 919
