Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "AssertMatchesAll" line 1, position 14
Keyword "extends" line 1, position 31
Identifier "RegexMatcher" line 1, position 39
Keyword "implements" line 1, position 52
Identifier "ValueAssertion" line 1, position 63
Operator "<" line 1, position 77
Identifier "Matcher" line 1, position 78
Operator ">" line 1, position 85
Separator "{" line 1, position 87
Modifier "private" line 1, position 89
Modifier "final" line 1, position 97
Modifier "static" line 1, position 103
Identifier "String" line 1, position 110
Identifier "message" line 1, position 117
Operator "=" line 1, position 125
String ""argument '%s' value was: %s, did not match: %s, in tuple: %s"" line 1, position 127
Separator ";" line 1, position 189
Annotation "@" line 1, position 191
Identifier "ConstructorProperties" line 1, position 192
Separator "(" line 1, position 213
Separator "{" line 1, position 214
String ""patternString"" line 1, position 215
Separator "}" line 1, position 230
Separator ")" line 1, position 231
Modifier "public" line 1, position 233
Identifier "AssertMatchesAll" line 1, position 240
Separator "(" line 1, position 256
Identifier "String" line 1, position 258
Identifier "patternString" line 1, position 265
Separator ")" line 1, position 279
Separator "{" line 1, position 281
Keyword "super" line 1, position 283
Separator "(" line 1, position 288
Identifier "patternString" line 1, position 290
Separator "," line 1, position 303
Boolean "false" line 1, position 305
Separator ")" line 1, position 311
Separator ";" line 1, position 312
Separator "}" line 1, position 314
Annotation "@" line 1, position 316
Identifier "ConstructorProperties" line 1, position 317
Separator "(" line 1, position 338
Separator "{" line 1, position 339
String ""patternString"" line 1, position 340
Separator "," line 1, position 355
String ""negateMatch"" line 1, position 357
Separator "}" line 1, position 370
Separator ")" line 1, position 371
Modifier "public" line 1, position 373
Identifier "AssertMatchesAll" line 1, position 380
Separator "(" line 1, position 396
Identifier "String" line 1, position 398
Identifier "patternString" line 1, position 405
Separator "," line 1, position 418
BasicType "boolean" line 1, position 420
Identifier "negateMatch" line 1, position 428
Separator ")" line 1, position 440
Separator "{" line 1, position 442
Keyword "super" line 1, position 444
Separator "(" line 1, position 449
Identifier "patternString" line 1, position 451
Separator "," line 1, position 464
Identifier "negateMatch" line 1, position 466
Separator ")" line 1, position 478
Separator ";" line 1, position 479
Separator "}" line 1, position 481
Annotation "@" line 1, position 483
Identifier "Override" line 1, position 484
Modifier "public" line 1, position 493
BasicType "boolean" line 1, position 500
Identifier "supportsPlannerLevel" line 1, position 508
Separator "(" line 1, position 528
Identifier "PlannerLevel" line 1, position 530
Identifier "plannerLevel" line 1, position 543
Separator ")" line 1, position 556
Separator "{" line 1, position 558
Keyword "return" line 1, position 560
Identifier "plannerLevel" line 1, position 567
Keyword "instanceof" line 1, position 580
Identifier "AssertionLevel" line 1, position 591
Separator ";" line 1, position 605
Separator "}" line 1, position 607
Annotation "@" line 1, position 609
Identifier "Override" line 1, position 610
Modifier "public" line 1, position 619
Keyword "void" line 1, position 626
Identifier "doAssert" line 1, position 631
Separator "(" line 1, position 639
Identifier "FlowProcess" line 1, position 641
Identifier "flowProcess" line 1, position 653
Separator "," line 1, position 664
Identifier "ValueAssertionCall" line 1, position 666
Operator "<" line 1, position 684
Identifier "Matcher" line 1, position 685
Operator ">" line 1, position 692
Identifier "assertionCall" line 1, position 694
Separator ")" line 1, position 708
Separator "{" line 1, position 710
Identifier "TupleEntry" line 1, position 712
Identifier "input" line 1, position 723
Operator "=" line 1, position 729
Identifier "assertionCall" line 1, position 731
Separator "." line 1, position 744
Identifier "getArguments" line 1, position 745
Separator "(" line 1, position 757
Separator ")" line 1, position 758
Separator ";" line 1, position 759
BasicType "int" line 1, position 761
Identifier "pos" line 1, position 765
Operator "=" line 1, position 769
Identifier "matchEachElementPos" line 1, position 771
Separator "(" line 1, position 790
Identifier "assertionCall" line 1, position 792
Separator "." line 1, position 805
Identifier "getContext" line 1, position 806
Separator "(" line 1, position 816
Separator ")" line 1, position 817
Separator "," line 1, position 818
Identifier "input" line 1, position 820
Separator ")" line 1, position 826
Separator ";" line 1, position 827
Keyword "if" line 1, position 829
Separator "(" line 1, position 831
Identifier "pos" line 1, position 833
Operator "!=" line 1, position 837
Operator "-" line 1, position 840
DecimalInteger "1" line 1, position 841
Separator ")" line 1, position 843
Identifier "BaseAssertion" line 1, position 845
Separator "." line 1, position 858
Identifier "throwFail" line 1, position 859
Separator "(" line 1, position 868
Identifier "message" line 1, position 870
Separator "," line 1, position 877
Identifier "input" line 1, position 879
Separator "." line 1, position 884
Identifier "getFields" line 1, position 885
Separator "(" line 1, position 894
Separator ")" line 1, position 895
Separator "." line 1, position 896
Identifier "get" line 1, position 897
Separator "(" line 1, position 900
Identifier "pos" line 1, position 902
Separator ")" line 1, position 906
Separator "," line 1, position 907
Identifier "input" line 1, position 909
Separator "." line 1, position 914
Identifier "getObject" line 1, position 915
Separator "(" line 1, position 924
Identifier "pos" line 1, position 926
Separator ")" line 1, position 930
Separator "," line 1, position 931
Identifier "patternString" line 1, position 933
Separator "," line 1, position 946
Identifier "input" line 1, position 948
Separator "." line 1, position 953
Identifier "getTuple" line 1, position 954
Separator "(" line 1, position 962
Separator ")" line 1, position 963
Separator "." line 1, position 964
Identifier "print" line 1, position 965
Separator "(" line 1, position 970
Separator ")" line 1, position 971
Separator ")" line 1, position 973
Separator ";" line 1, position 974
Separator "}" line 1, position 976
Separator "}" line 1, position 978
