Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "X" line 1, position 14
Keyword "extends" line 1, position 16
Identifier "A" line 1, position 24
Separator "{" line 1, position 26
Modifier "public" line 1, position 28
BasicType "int" line 1, position 35
Identifier "x" line 1, position 39
Operator "=" line 1, position 41
Identifier "a" line 1, position 43
Separator ";" line 1, position 44
Separator "}" line 1, position 46
