Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "JSONBuildIntoFunction" line 1, position 14
Keyword "extends" line 1, position 36
Identifier "NestedBaseBuildFunction" line 1, position 44
Operator "<" line 1, position 67
Identifier "JsonNode" line 1, position 68
Separator "," line 1, position 76
Identifier "ArrayNode" line 1, position 78
Operator ">" line 1, position 87
Separator "{" line 1, position 89
Annotation "@" line 1, position 91
Identifier "ConstructorProperties" line 1, position 92
Separator "(" line 1, position 113
Separator "{" line 1, position 114
String ""fieldDeclaration"" line 1, position 115
Separator "," line 1, position 133
String ""buildSpecs"" line 1, position 135
Separator "}" line 1, position 147
Separator ")" line 1, position 148
Modifier "public" line 1, position 150
Identifier "JSONBuildIntoFunction" line 1, position 157
Separator "(" line 1, position 178
Identifier "Fields" line 1, position 180
Identifier "fieldDeclaration" line 1, position 187
Separator "," line 1, position 203
Identifier "BuildSpec" line 1, position 205
Operator "..." line 1, position 214
Identifier "buildSpecs" line 1, position 218
Separator ")" line 1, position 229
Separator "{" line 1, position 231
Keyword "super" line 1, position 233
Separator "(" line 1, position 238
Identifier "JSONCoercibleType" line 1, position 240
Separator "." line 1, position 257
Identifier "TYPE" line 1, position 258
Separator "," line 1, position 262
Identifier "fieldDeclaration" line 1, position 264
Separator "," line 1, position 280
Identifier "buildSpecs" line 1, position 282
Separator ")" line 1, position 293
Separator ";" line 1, position 294
Separator "}" line 1, position 296
Annotation "@" line 1, position 298
Identifier "ConstructorProperties" line 1, position 299
Separator "(" line 1, position 320
Separator "{" line 1, position 321
String ""coercibleType"" line 1, position 322
Separator "," line 1, position 337
String ""fieldDeclaration"" line 1, position 339
Separator "," line 1, position 357
String ""buildSpecs"" line 1, position 359
Separator "}" line 1, position 371
Separator ")" line 1, position 372
Modifier "public" line 1, position 374
Identifier "JSONBuildIntoFunction" line 1, position 381
Separator "(" line 1, position 402
Identifier "JSONCoercibleType" line 1, position 404
Identifier "coercibleType" line 1, position 422
Separator "," line 1, position 435
Identifier "Fields" line 1, position 437
Identifier "fieldDeclaration" line 1, position 444
Separator "," line 1, position 460
Identifier "BuildSpec" line 1, position 462
Operator "..." line 1, position 471
Identifier "buildSpecs" line 1, position 475
Separator ")" line 1, position 486
Separator "{" line 1, position 488
Keyword "super" line 1, position 490
Separator "(" line 1, position 495
Identifier "coercibleType" line 1, position 497
Separator "," line 1, position 510
Identifier "fieldDeclaration" line 1, position 512
Separator "," line 1, position 528
Identifier "buildSpecs" line 1, position 530
Separator ")" line 1, position 541
Separator ";" line 1, position 542
Separator "}" line 1, position 544
Annotation "@" line 1, position 546
Identifier "Override" line 1, position 547
Modifier "protected" line 1, position 556
BasicType "boolean" line 1, position 566
Identifier "isInto" line 1, position 574
Separator "(" line 1, position 580
Separator ")" line 1, position 581
Separator "{" line 1, position 583
Keyword "return" line 1, position 585
Boolean "true" line 1, position 592
Separator ";" line 1, position 596
Separator "}" line 1, position 598
Separator "}" line 1, position 600
