Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "StringKeyStrategy" line 1, position 14
Keyword "extends" line 1, position 32
Identifier "AbstractKeyStrategy" line 1, position 40
Separator "{" line 1, position 60
Modifier "protected" line 1, position 62
Identifier "String" line 1, position 72
Identifier "transformKeyObject" line 1, position 79
Separator "(" line 1, position 97
Identifier "Object" line 1, position 98
Identifier "key" line 1, position 105
Separator ")" line 1, position 108
Separator "{" line 1, position 110
Identifier "String" line 1, position 112
Identifier "stringKey" line 1, position 119
Operator "=" line 1, position 129
Identifier "String" line 1, position 131
Separator "." line 1, position 137
Identifier "valueOf" line 1, position 138
Separator "(" line 1, position 145
Identifier "key" line 1, position 146
Separator ")" line 1, position 149
Separator ";" line 1, position 150
Identifier "log" line 1, position 152
Separator "." line 1, position 155
Identifier "debug" line 1, position 156
Separator "(" line 1, position 161
String ""Transformed key [{}] to string [{}]"" line 1, position 162
Separator "," line 1, position 199
Identifier "key" line 1, position 201
Separator "," line 1, position 204
Identifier "stringKey" line 1, position 206
Separator ")" line 1, position 215
Separator ";" line 1, position 216
Keyword "return" line 1, position 218
Identifier "stringKey" line 1, position 225
Separator ";" line 1, position 234
Separator "}" line 1, position 236
Separator "}" line 1, position 238
