Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "KeyTupleSerializer" line 1, position 14
Keyword "extends" line 1, position 33
Identifier "BaseSerializer" line 1, position 41
Operator "<" line 1, position 55
Identifier "KeyTuple" line 1, position 56
Operator ">" line 1, position 64
Separator "{" line 1, position 66
Modifier "public" line 1, position 68
Identifier "KeyTupleSerializer" line 1, position 75
Separator "(" line 1, position 93
Identifier "TupleSerialization" line 1, position 95
Separator "." line 1, position 113
Identifier "SerializationElementWriter" line 1, position 114
Identifier "elementWriter" line 1, position 141
Separator ")" line 1, position 155
Separator "{" line 1, position 157
Keyword "super" line 1, position 159
Separator "(" line 1, position 164
Identifier "elementWriter" line 1, position 166
Separator ")" line 1, position 180
Separator ";" line 1, position 181
Identifier "setWriters" line 1, position 183
Separator "(" line 1, position 193
Identifier "elementWriter" line 1, position 195
Separator "." line 1, position 208
Identifier "getTupleSerialization" line 1, position 209
Separator "(" line 1, position 230
Separator ")" line 1, position 231
Separator "." line 1, position 232
Identifier "getKeyFields" line 1, position 233
Separator "(" line 1, position 245
Separator ")" line 1, position 246
Separator ")" line 1, position 248
Separator ";" line 1, position 249
Separator "}" line 1, position 251
Separator "}" line 1, position 253
