Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "PwDbHeaderOutput" line 1, position 14
Separator "{" line 1, position 31
Modifier "protected" line 1, position 33
BasicType "byte" line 1, position 43
Separator "[" line 1, position 47
Separator "]" line 1, position 48
Identifier "hashOfHeader" line 1, position 50
Operator "=" line 1, position 63
Null "null" line 1, position 65
Separator ";" line 1, position 69
Modifier "public" line 1, position 71
BasicType "byte" line 1, position 78
Separator "[" line 1, position 82
Separator "]" line 1, position 83
Identifier "getHashOfHeader" line 1, position 85
Separator "(" line 1, position 100
Separator ")" line 1, position 101
Separator "{" line 1, position 103
Keyword "return" line 1, position 105
Identifier "hashOfHeader" line 1, position 112
Separator ";" line 1, position 124
Separator "}" line 1, position 126
Separator "}" line 1, position 128
