Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "AssertionFailedError" line 1, position 14
Keyword "extends" line 1, position 35
Identifier "AssertionError" line 1, position 43
Separator "{" line 1, position 58
Modifier "private" line 1, position 60
Modifier "static" line 1, position 68
Modifier "final" line 1, position 75
BasicType "long" line 1, position 81
Identifier "serialVersionUID" line 1, position 86
Operator "=" line 1, position 103
DecimalInteger "1L" line 1, position 105
Separator ";" line 1, position 107
Modifier "public" line 1, position 109
Identifier "AssertionFailedError" line 1, position 116
Separator "(" line 1, position 136
Separator ")" line 1, position 137
Separator "{" line 1, position 139
Separator "}" line 1, position 141
Modifier "public" line 1, position 143
Identifier "AssertionFailedError" line 1, position 150
Separator "(" line 1, position 170
Identifier "String" line 1, position 171
Identifier "message" line 1, position 178
Separator ")" line 1, position 185
Separator "{" line 1, position 187
Keyword "super" line 1, position 189
Separator "(" line 1, position 194
Identifier "defaultString" line 1, position 195
Separator "(" line 1, position 208
Identifier "message" line 1, position 209
Separator ")" line 1, position 216
Separator ")" line 1, position 217
Separator ";" line 1, position 218
Separator "}" line 1, position 220
Modifier "private" line 1, position 222
Modifier "static" line 1, position 230
Identifier "String" line 1, position 237
Identifier "defaultString" line 1, position 244
Separator "(" line 1, position 257
Identifier "String" line 1, position 258
Identifier "message" line 1, position 265
Separator ")" line 1, position 272
Separator "{" line 1, position 274
Keyword "return" line 1, position 276
Identifier "message" line 1, position 283
Operator "==" line 1, position 291
Null "null" line 1, position 294
Operator "?" line 1, position 299
String """" line 1, position 301
Operator ":" line 1, position 304
Identifier "message" line 1, position 306
Separator ";" line 1, position 313
Separator "}" line 1, position 315
Separator "}" line 1, position 317
