Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "RunRules" line 1, position 14
Keyword "extends" line 1, position 23
Identifier "Statement" line 1, position 31
Separator "{" line 1, position 41
Modifier "private" line 1, position 43
Modifier "final" line 1, position 51
Identifier "Statement" line 1, position 57
Identifier "statement" line 1, position 67
Separator ";" line 1, position 76
Modifier "public" line 1, position 78
Identifier "RunRules" line 1, position 85
Separator "(" line 1, position 93
Identifier "Statement" line 1, position 94
Identifier "base" line 1, position 104
Separator "," line 1, position 108
Identifier "Iterable" line 1, position 110
Operator "<" line 1, position 118
Identifier "TestRule" line 1, position 119
Operator ">" line 1, position 127
Identifier "rules" line 1, position 129
Separator "," line 1, position 134
Identifier "Description" line 1, position 136
Identifier "description" line 1, position 148
Separator ")" line 1, position 159
Separator "{" line 1, position 161
Identifier "statement" line 1, position 163
Operator "=" line 1, position 173
Identifier "applyAll" line 1, position 175
Separator "(" line 1, position 183
Identifier "base" line 1, position 184
Separator "," line 1, position 188
Identifier "rules" line 1, position 190
Separator "," line 1, position 195
Identifier "description" line 1, position 197
Separator ")" line 1, position 208
Separator ";" line 1, position 209
Separator "}" line 1, position 211
Annotation "@" line 1, position 213
Identifier "Override" line 1, position 214
Modifier "public" line 1, position 223
Keyword "void" line 1, position 230
Identifier "evaluate" line 1, position 235
Separator "(" line 1, position 243
Separator ")" line 1, position 244
Keyword "throws" line 1, position 246
Identifier "Throwable" line 1, position 253
Separator "{" line 1, position 263
Identifier "statement" line 1, position 265
Separator "." line 1, position 274
Identifier "evaluate" line 1, position 275
Separator "(" line 1, position 283
Separator ")" line 1, position 284
Separator ";" line 1, position 285
Separator "}" line 1, position 287
Modifier "private" line 1, position 289
Modifier "static" line 1, position 297
Identifier "Statement" line 1, position 304
Identifier "applyAll" line 1, position 314
Separator "(" line 1, position 322
Identifier "Statement" line 1, position 323
Identifier "result" line 1, position 333
Separator "," line 1, position 339
Identifier "Iterable" line 1, position 341
Operator "<" line 1, position 349
Identifier "TestRule" line 1, position 350
Operator ">" line 1, position 358
Identifier "rules" line 1, position 360
Separator "," line 1, position 365
Identifier "Description" line 1, position 367
Identifier "description" line 1, position 379
Separator ")" line 1, position 390
Separator "{" line 1, position 392
Keyword "for" line 1, position 394
Separator "(" line 1, position 398
Identifier "TestRule" line 1, position 399
Identifier "each" line 1, position 408
Operator ":" line 1, position 413
Identifier "rules" line 1, position 415
Separator ")" line 1, position 420
Separator "{" line 1, position 422
Identifier "result" line 1, position 424
Operator "=" line 1, position 431
Identifier "each" line 1, position 433
Separator "." line 1, position 437
Identifier "apply" line 1, position 438
Separator "(" line 1, position 443
Identifier "result" line 1, position 444
Separator "," line 1, position 450
Identifier "description" line 1, position 452
Separator ")" line 1, position 463
Separator ";" line 1, position 464
Separator "}" line 1, position 466
Keyword "return" line 1, position 468
Identifier "result" line 1, position 475
Separator ";" line 1, position 481
Separator "}" line 1, position 483
Separator "}" line 1, position 485
