Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "ConnectbotJUnitRunner" line 1, position 14
Keyword "extends" line 1, position 36
Identifier "AndroidJUnitRunner" line 1, position 44
Separator "{" line 1, position 63
Annotation "@" line 1, position 65
Identifier "Override" line 1, position 66
Modifier "public" line 1, position 75
Keyword "void" line 1, position 82
Identifier "onStart" line 1, position 87
Separator "(" line 1, position 94
Separator ")" line 1, position 95
Separator "{" line 1, position 97
Identifier "TestButler" line 1, position 99
Separator "." line 1, position 109
Identifier "setup" line 1, position 110
Separator "(" line 1, position 115
Identifier "getTargetContext" line 1, position 116
Separator "(" line 1, position 132
Separator ")" line 1, position 133
Separator ")" line 1, position 134
Separator ";" line 1, position 135
Keyword "super" line 1, position 137
Separator "." line 1, position 142
Identifier "onStart" line 1, position 143
Separator "(" line 1, position 150
Separator ")" line 1, position 151
Separator ";" line 1, position 152
Separator "}" line 1, position 154
Annotation "@" line 1, position 156
Identifier "Override" line 1, position 157
Modifier "public" line 1, position 166
Keyword "void" line 1, position 173
Identifier "finish" line 1, position 178
Separator "(" line 1, position 184
BasicType "int" line 1, position 185
Identifier "resultCode" line 1, position 189
Separator "," line 1, position 199
Identifier "Bundle" line 1, position 201
Identifier "results" line 1, position 208
Separator ")" line 1, position 215
Separator "{" line 1, position 217
Identifier "TestButler" line 1, position 219
Separator "." line 1, position 229
Identifier "teardown" line 1, position 230
Separator "(" line 1, position 238
Identifier "getTargetContext" line 1, position 239
Separator "(" line 1, position 255
Separator ")" line 1, position 256
Separator ")" line 1, position 257
Separator ";" line 1, position 258
Keyword "super" line 1, position 260
Separator "." line 1, position 265
Identifier "finish" line 1, position 266
Separator "(" line 1, position 272
Identifier "resultCode" line 1, position 273
Separator "," line 1, position 283
Identifier "results" line 1, position 285
Separator ")" line 1, position 292
Separator ";" line 1, position 293
Separator "}" line 1, position 295
Separator "}" line 1, position 297
