Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "Context" line 1, position 14
Separator "{" line 1, position 22
Identifier "Node" line 1, position 24
Identifier "rootNode" line 1, position 29
Operator "=" line 1, position 38
Null "null" line 1, position 40
Separator ";" line 1, position 44
Modifier "public" line 1, position 46
Keyword "void" line 1, position 53
Identifier "reset" line 1, position 58
Separator "(" line 1, position 63
Separator ")" line 1, position 64
Separator "{" line 1, position 66
Identifier "rootNode" line 1, position 68
Operator "=" line 1, position 77
Identifier "getRootNode" line 1, position 79
Separator "(" line 1, position 90
Separator ")" line 1, position 91
Separator ";" line 1, position 92
Separator "}" line 1, position 94
Separator "}" line 1, position 96
