Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "CancelledOperationStatus" line 1, position 14
Keyword "extends" line 1, position 39
Identifier "OperationStatus" line 1, position 47
Separator "{" line 1, position 63
Modifier "public" line 1, position 65
Identifier "CancelledOperationStatus" line 1, position 72
Separator "(" line 1, position 96
Separator ")" line 1, position 97
Separator "{" line 1, position 99
Keyword "super" line 1, position 101
Separator "(" line 1, position 106
Boolean "false" line 1, position 107
Separator "," line 1, position 112
String ""cancelled"" line 1, position 114
Separator "," line 1, position 125
Identifier "StatusCode" line 1, position 127
Separator "." line 1, position 137
Identifier "CANCELLED" line 1, position 138
Separator ")" line 1, position 147
Separator ";" line 1, position 148
Separator "}" line 1, position 150
Separator "}" line 1, position 152
