Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "TupleSerializer" line 1, position 14
Keyword "extends" line 1, position 30
Identifier "BaseSerializer" line 1, position 38
Operator "<" line 1, position 52
Identifier "Tuple" line 1, position 53
Operator ">" line 1, position 58
Separator "{" line 1, position 60
Modifier "public" line 1, position 62
Identifier "TupleSerializer" line 1, position 69
Separator "(" line 1, position 84
Identifier "TupleSerialization" line 1, position 86
Separator "." line 1, position 104
Identifier "SerializationElementWriter" line 1, position 105
Identifier "elementWriter" line 1, position 132
Separator ")" line 1, position 146
Separator "{" line 1, position 148
Keyword "super" line 1, position 150
Separator "(" line 1, position 155
Identifier "elementWriter" line 1, position 157
Separator ")" line 1, position 171
Separator ";" line 1, position 172
Separator "}" line 1, position 174
Modifier "public" line 1, position 176
Keyword "void" line 1, position 183
Identifier "serialize" line 1, position 188
Separator "(" line 1, position 197
Identifier "Tuple" line 1, position 199
Identifier "tuple" line 1, position 205
Separator ")" line 1, position 211
Keyword "throws" line 1, position 213
Identifier "IOException" line 1, position 220
Separator "{" line 1, position 232
Identifier "outputStream" line 1, position 234
Separator "." line 1, position 246
Identifier "writeTuple" line 1, position 247
Separator "(" line 1, position 257
Identifier "tuple" line 1, position 259
Separator ")" line 1, position 265
Separator ";" line 1, position 266
Separator "}" line 1, position 268
Separator "}" line 1, position 270
