Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "Blort" line 1, position 14
Separator "{" line 1, position 20
Modifier "public" line 1, position 22
Modifier "static" line 1, position 29
BasicType "boolean" line 1, position 36
Identifier "test" line 1, position 44
Separator "(" line 1, position 48
Identifier "Object" line 1, position 49
Identifier "x" line 1, position 56
Separator ")" line 1, position 57
Separator "{" line 1, position 59
Keyword "return" line 1, position 61
Identifier "x" line 1, position 68
Keyword "instanceof" line 1, position 70
Identifier "Blort" line 1, position 81
Separator ";" line 1, position 86
Separator "}" line 1, position 88
Separator "}" line 1, position 90
