Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "BuildSpec" line 1, position 14
Keyword "extends" line 1, position 24
Identifier "heretical" line 1, position 32
Separator "." line 1, position 41
Identifier "pointer" line 1, position 42
Separator "." line 1, position 49
Identifier "operation" line 1, position 50
Separator "." line 1, position 59
Identifier "BuildSpec" line 1, position 60
Operator "<" line 1, position 69
Identifier "BuildSpec" line 1, position 70
Operator ">" line 1, position 79
Separator "{" line 1, position 81
Modifier "public" line 1, position 83
Identifier "BuildSpec" line 1, position 90
Separator "(" line 1, position 99
Separator ")" line 1, position 100
Separator "{" line 1, position 102
Separator "}" line 1, position 104
Modifier "public" line 1, position 106
Identifier "BuildSpec" line 1, position 113
Separator "(" line 1, position 122
Identifier "Type" line 1, position 124
Identifier "defaultType" line 1, position 129
Separator ")" line 1, position 141
Separator "{" line 1, position 143
Keyword "super" line 1, position 145
Separator "(" line 1, position 150
Identifier "defaultType" line 1, position 152
Separator ")" line 1, position 164
Separator ";" line 1, position 165
Separator "}" line 1, position 167
Modifier "public" line 1, position 169
Identifier "BuildSpec" line 1, position 176
Separator "(" line 1, position 185
Identifier "String" line 1, position 187
Identifier "intoPointer" line 1, position 194
Separator ")" line 1, position 206
Separator "{" line 1, position 208
Keyword "super" line 1, position 210
Separator "(" line 1, position 215
Identifier "intoPointer" line 1, position 217
Separator ")" line 1, position 229
Separator ";" line 1, position 230
Separator "}" line 1, position 232
Modifier "public" line 1, position 234
Identifier "BuildSpec" line 1, position 241
Separator "(" line 1, position 250
Identifier "String" line 1, position 252
Identifier "intoPointer" line 1, position 259
Separator "," line 1, position 270
Identifier "Type" line 1, position 272
Identifier "defaultType" line 1, position 277
Separator ")" line 1, position 289
Separator "{" line 1, position 291
Keyword "super" line 1, position 293
Separator "(" line 1, position 298
Identifier "intoPointer" line 1, position 300
Separator "," line 1, position 311
Identifier "defaultType" line 1, position 313
Separator ")" line 1, position 325
Separator ";" line 1, position 326
Separator "}" line 1, position 328
Separator "}" line 1, position 330
