Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "FlowSkipIfSinkNotStale" line 1, position 14
Keyword "implements" line 1, position 37
Identifier "FlowSkipStrategy" line 1, position 48
Separator "{" line 1, position 65
Modifier "public" line 1, position 67
BasicType "boolean" line 1, position 74
Identifier "skipFlow" line 1, position 82
Separator "(" line 1, position 90
Identifier "Flow" line 1, position 92
Identifier "flow" line 1, position 97
Separator ")" line 1, position 102
Keyword "throws" line 1, position 104
Identifier "IOException" line 1, position 111
Separator "{" line 1, position 123
BasicType "long" line 1, position 125
Identifier "sinkModified" line 1, position 130
Operator "=" line 1, position 143
Identifier "flow" line 1, position 145
Separator "." line 1, position 149
Identifier "getSinkModified" line 1, position 150
Separator "(" line 1, position 165
Separator ")" line 1, position 166
Separator ";" line 1, position 167
Keyword "return" line 1, position 169
Identifier "sinkModified" line 1, position 176
Operator ">" line 1, position 189
DecimalInteger "0" line 1, position 191
Operator "&&" line 1, position 193
Operator "!" line 1, position 196
Identifier "flow" line 1, position 197
Separator "." line 1, position 201
Identifier "areSourcesNewer" line 1, position 202
Separator "(" line 1, position 217
Identifier "sinkModified" line 1, position 219
Separator ")" line 1, position 232
Separator ";" line 1, position 233
Separator "}" line 1, position 235
Separator "}" line 1, position 237
