Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "BottomUpJoinedBoundariesNodePartitioner" line 1, position 14
Keyword "extends" line 1, position 54
Identifier "ExpressionRulePartitioner" line 1, position 62
Separator "{" line 1, position 88
Modifier "public" line 1, position 90
Identifier "BottomUpJoinedBoundariesNodePartitioner" line 1, position 97
Separator "(" line 1, position 136
Separator ")" line 1, position 137
Separator "{" line 1, position 139
Keyword "super" line 1, position 141
Separator "(" line 1, position 146
Identifier "PartitionNodes" line 1, position 148
Separator "," line 1, position 162
Keyword "new" line 1, position 164
Identifier "RuleExpression" line 1, position 168
Separator "(" line 1, position 182
Keyword "new" line 1, position 184
Identifier "NoGroupJoinMergeBoundaryTapExpressionGraph" line 1, position 188
Separator "(" line 1, position 230
Separator ")" line 1, position 231
Separator "," line 1, position 232
Keyword "new" line 1, position 234
Identifier "BottomUpConsecutiveBoundariesExpressionGraph" line 1, position 238
Separator "(" line 1, position 282
Separator ")" line 1, position 283
Separator ")" line 1, position 285
Separator "," line 1, position 286
Keyword "new" line 1, position 288
Identifier "ElementAnnotation" line 1, position 292
Separator "(" line 1, position 309
Identifier "ElementCapture" line 1, position 311
Separator "." line 1, position 325
Identifier "Primary" line 1, position 326
Separator "," line 1, position 333
Identifier "IORole" line 1, position 335
Separator "." line 1, position 341
Identifier "sink" line 1, position 342
Separator ")" line 1, position 347
Separator ")" line 1, position 349
Separator ";" line 1, position 350
Separator "}" line 1, position 352
Separator "}" line 1, position 354
