Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "MultiTapGroupExpressionGraph" line 1, position 14
Keyword "extends" line 1, position 43
Identifier "ExpressionGraph" line 1, position 51
Separator "{" line 1, position 67
Modifier "public" line 1, position 69
Identifier "MultiTapGroupExpressionGraph" line 1, position 76
Separator "(" line 1, position 104
Separator ")" line 1, position 105
Separator "{" line 1, position 107
Keyword "super" line 1, position 109
Separator "(" line 1, position 114
Identifier "SearchOrder" line 1, position 116
Separator "." line 1, position 127
Identifier "ReverseTopological" line 1, position 128
Separator ")" line 1, position 147
Separator ";" line 1, position 148
Keyword "this" line 1, position 150
Separator "." line 1, position 155
Identifier "arc" line 1, position 156
Separator "(" line 1, position 159
Keyword "new" line 1, position 161
Identifier "FlowElementExpression" line 1, position 165
Separator "(" line 1, position 186
Identifier "Tap" line 1, position 188
Separator "." line 1, position 191
Keyword "class" line 1, position 192
Separator ")" line 1, position 198
Separator "," line 1, position 199
Identifier "ScopeExpression" line 1, position 201
Separator "." line 1, position 216
Identifier "ALL" line 1, position 217
Separator "," line 1, position 220
Keyword "new" line 1, position 222
Identifier "FlowElementExpression" line 1, position 226
Separator "(" line 1, position 247
Identifier "ElementCapture" line 1, position 249
Separator "." line 1, position 263
Identifier "Primary" line 1, position 264
Separator "," line 1, position 271
Identifier "Group" line 1, position 273
Separator "." line 1, position 278
Keyword "class" line 1, position 279
Separator ")" line 1, position 285
Separator ")" line 1, position 287
Separator ";" line 1, position 288
Separator "}" line 1, position 290
Separator "}" line 1, position 292
