Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "NullBuilder" line 1, position 14
Keyword "extends" line 1, position 26
Identifier "RunnerBuilder" line 1, position 34
Separator "{" line 1, position 48
Annotation "@" line 1, position 50
Identifier "Override" line 1, position 51
Modifier "public" line 1, position 60
Identifier "Runner" line 1, position 67
Identifier "runnerForClass" line 1, position 74
Separator "(" line 1, position 88
Identifier "Class" line 1, position 89
Operator "<" line 1, position 94
Operator "?" line 1, position 95
Operator ">" line 1, position 96
Identifier "each" line 1, position 98
Separator ")" line 1, position 102
Keyword "throws" line 1, position 104
Identifier "Throwable" line 1, position 111
Separator "{" line 1, position 121
Keyword "return" line 1, position 123
Null "null" line 1, position 130
Separator ";" line 1, position 134
Separator "}" line 1, position 136
Separator "}" line 1, position 138
