Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "NoGroupTapExpressionGraph" line 1, position 14
Keyword "extends" line 1, position 40
Identifier "ExpressionGraph" line 1, position 48
Separator "{" line 1, position 64
Modifier "public" line 1, position 66
Identifier "NoGroupTapExpressionGraph" line 1, position 73
Separator "(" line 1, position 98
Separator ")" line 1, position 99
Separator "{" line 1, position 101
Keyword "super" line 1, position 103
Separator "(" line 1, position 108
Identifier "not" line 1, position 110
Separator "(" line 1, position 113
Identifier "OrElementExpression" line 1, position 115
Separator "." line 1, position 134
Identifier "or" line 1, position 135
Separator "(" line 1, position 137
Identifier "ElementCapture" line 1, position 139
Separator "." line 1, position 153
Identifier "Primary" line 1, position 154
Separator "," line 1, position 161
Keyword "new" line 1, position 163
Identifier "FlowElementExpression" line 1, position 167
Separator "(" line 1, position 188
Identifier "Extent" line 1, position 190
Separator "." line 1, position 196
Keyword "class" line 1, position 197
Separator ")" line 1, position 203
Separator "," line 1, position 204
Keyword "new" line 1, position 206
Identifier "FlowElementExpression" line 1, position 210
Separator "(" line 1, position 231
Identifier "Group" line 1, position 233
Separator "." line 1, position 238
Keyword "class" line 1, position 239
Separator ")" line 1, position 245
Separator "," line 1, position 246
Keyword "new" line 1, position 248
Identifier "FlowElementExpression" line 1, position 252
Separator "(" line 1, position 273
Identifier "Tap" line 1, position 275
Separator "." line 1, position 278
Keyword "class" line 1, position 279
Separator ")" line 1, position 285
Separator ")" line 1, position 287
Separator ")" line 1, position 289
Separator ")" line 1, position 291
Separator ";" line 1, position 292
Separator "}" line 1, position 294
Separator "}" line 1, position 296
