Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "LogicalMergeAnnotator" line 1, position 14
Keyword "extends" line 1, position 36
Identifier "RuleAnnotationTransformer" line 1, position 44
Separator "{" line 1, position 70
Modifier "public" line 1, position 72
Identifier "LogicalMergeAnnotator" line 1, position 79
Separator "(" line 1, position 100
Separator ")" line 1, position 101
Separator "{" line 1, position 103
Keyword "super" line 1, position 105
Separator "(" line 1, position 110
Identifier "PlanPhase" line 1, position 112
Separator "." line 1, position 121
Identifier "PreResolveAssembly" line 1, position 122
Separator "," line 1, position 140
Keyword "new" line 1, position 142
Identifier "LogicalMergeAnnotatorExpression" line 1, position 146
Separator "(" line 1, position 177
Separator ")" line 1, position 178
Separator "," line 1, position 179
Keyword "new" line 1, position 181
Identifier "ElementAnnotation" line 1, position 185
Separator "(" line 1, position 202
Identifier "ElementCapture" line 1, position 204
Separator "." line 1, position 218
Identifier "Secondary" line 1, position 219
Separator "," line 1, position 228
Identifier "RoleMode" line 1, position 230
Separator "." line 1, position 238
Identifier "Logical" line 1, position 239
Separator ")" line 1, position 247
Separator ")" line 1, position 249
Separator ";" line 1, position 250
Separator "}" line 1, position 252
Separator "}" line 1, position 254
