Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "Blort" line 1, position 14
Separator "{" line 1, position 20
Modifier "private" line 1, position 22
Modifier "static" line 1, position 30
Identifier "RuntimeException" line 1, position 37
Identifier "theException" line 1, position 54
Operator "=" line 1, position 67
Keyword "new" line 1, position 69
Identifier "RuntimeException" line 1, position 73
Separator "(" line 1, position 89
Separator ")" line 1, position 90
Separator ";" line 1, position 91
Modifier "public" line 1, position 93
Modifier "static" line 1, position 100
Keyword "void" line 1, position 107
Identifier "test1" line 1, position 112
Separator "(" line 1, position 117
Separator ")" line 1, position 118
Separator "{" line 1, position 120
Keyword "throw" line 1, position 122
Identifier "theException" line 1, position 128
Separator ";" line 1, position 140
Separator "}" line 1, position 142
Modifier "public" line 1, position 144
Modifier "static" line 1, position 151
BasicType "int" line 1, position 158
Identifier "test2" line 1, position 162
Separator "(" line 1, position 167
Separator ")" line 1, position 168
Separator "{" line 1, position 170
Keyword "try" line 1, position 172
Separator "{" line 1, position 176
Keyword "throw" line 1, position 178
Identifier "theException" line 1, position 184
Separator ";" line 1, position 196
Separator "}" line 1, position 198
Keyword "catch" line 1, position 200
Separator "(" line 1, position 206
Identifier "RuntimeException" line 1, position 207
Identifier "ex" line 1, position 224
Separator ")" line 1, position 226
Separator "{" line 1, position 228
Keyword "return" line 1, position 230
DecimalInteger "1" line 1, position 237
Separator ";" line 1, position 238
Separator "}" line 1, position 240
Separator "}" line 1, position 242
Separator "}" line 1, position 244
