Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "NotVoidTestCase" line 1, position 14
Keyword "extends" line 1, position 30
Identifier "TestCase" line 1, position 38
Separator "{" line 1, position 47
Modifier "public" line 1, position 49
BasicType "int" line 1, position 56
Identifier "testNotVoid" line 1, position 60
Separator "(" line 1, position 71
Separator ")" line 1, position 72
Separator "{" line 1, position 74
Keyword "return" line 1, position 76
DecimalInteger "1" line 1, position 83
Separator ";" line 1, position 84
Separator "}" line 1, position 86
Modifier "public" line 1, position 88
Keyword "void" line 1, position 95
Identifier "testVoid" line 1, position 100
Separator "(" line 1, position 108
Separator ")" line 1, position 109
Separator "{" line 1, position 111
Separator "}" line 1, position 113
Separator "}" line 1, position 115
