Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "HintsActivity" line 1, position 14
Keyword "extends" line 1, position 28
Identifier "AppCompatActivity" line 1, position 36
Separator "{" line 1, position 54
Annotation "@" line 1, position 56
Identifier "Override" line 1, position 57
Modifier "protected" line 1, position 66
Keyword "void" line 1, position 76
Identifier "onCreate" line 1, position 81
Separator "(" line 1, position 89
Identifier "Bundle" line 1, position 90
Identifier "savedInstanceState" line 1, position 97
Separator ")" line 1, position 115
Separator "{" line 1, position 117
Keyword "super" line 1, position 119
Separator "." line 1, position 124
Identifier "onCreate" line 1, position 125
Separator "(" line 1, position 133
Identifier "savedInstanceState" line 1, position 134
Separator ")" line 1, position 152
Separator ";" line 1, position 153
Identifier "setContentView" line 1, position 155
Separator "(" line 1, position 169
Identifier "R" line 1, position 170
Separator "." line 1, position 171
Identifier "layout" line 1, position 172
Separator "." line 1, position 178
Identifier "act_hints" line 1, position 179
Separator ")" line 1, position 188
Separator ";" line 1, position 189
Separator "}" line 1, position 191
Separator "}" line 1, position 193
