Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "BalanceNonSafeSplitExpression" line 1, position 14
Keyword "extends" line 1, position 44
Identifier "RuleExpression" line 1, position 52
Separator "{" line 1, position 67
Modifier "public" line 1, position 69
Identifier "BalanceNonSafeSplitExpression" line 1, position 76
Separator "(" line 1, position 105
Separator ")" line 1, position 106
Separator "{" line 1, position 108
Keyword "super" line 1, position 110
Separator "(" line 1, position 115
Keyword "new" line 1, position 117
Identifier "NonSafeAndSplitAndSyncPipeExpressionGraph" line 1, position 121
Separator "(" line 1, position 162
Separator ")" line 1, position 163
Separator "," line 1, position 164
Keyword "new" line 1, position 166
Identifier "ExpressionGraph" line 1, position 170
Separator "(" line 1, position 185
Separator ")" line 1, position 186
Separator "." line 1, position 188
Identifier "arcs" line 1, position 189
Separator "(" line 1, position 193
Keyword "new" line 1, position 195
Identifier "FlowElementExpression" line 1, position 199
Separator "(" line 1, position 220
Identifier "Tap" line 1, position 222
Separator "." line 1, position 225
Keyword "class" line 1, position 226
Separator ")" line 1, position 232
Separator "," line 1, position 233
Keyword "new" line 1, position 235
Identifier "NonSafeOperationExpression" line 1, position 239
Separator "(" line 1, position 265
Identifier "TypeExpression" line 1, position 267
Separator "." line 1, position 281
Identifier "Topo" line 1, position 282
Separator "." line 1, position 286
Identifier "SplitOnly" line 1, position 287
Separator ")" line 1, position 297
Separator ")" line 1, position 299
Separator "," line 1, position 300
Keyword "new" line 1, position 302
Identifier "ExpressionGraph" line 1, position 306
Separator "(" line 1, position 321
Separator ")" line 1, position 322
Separator "." line 1, position 324
Identifier "arcs" line 1, position 325
Separator "(" line 1, position 329
Keyword "new" line 1, position 331
Identifier "FlowElementExpression" line 1, position 335
Separator "(" line 1, position 356
Identifier "ElementCapture" line 1, position 358
Separator "." line 1, position 372
Identifier "Primary" line 1, position 373
Separator "," line 1, position 380
Identifier "Pipe" line 1, position 382
Separator "." line 1, position 386
Keyword "class" line 1, position 387
Separator "," line 1, position 392
Identifier "TypeExpression" line 1, position 394
Separator "." line 1, position 408
Identifier "Topo" line 1, position 409
Separator "." line 1, position 413
Identifier "Tail" line 1, position 414
Separator ")" line 1, position 419
Separator ")" line 1, position 421
Separator ")" line 1, position 423
Separator ";" line 1, position 424
Separator "}" line 1, position 426
Separator "}" line 1, position 428
