Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "AllTests" line 1, position 14
Keyword "extends" line 1, position 23
Identifier "SuiteMethod" line 1, position 31
Separator "{" line 1, position 43
Modifier "public" line 1, position 45
Identifier "AllTests" line 1, position 52
Separator "(" line 1, position 60
Identifier "Class" line 1, position 61
Operator "<" line 1, position 66
Operator "?" line 1, position 67
Operator ">" line 1, position 68
Identifier "klass" line 1, position 70
Separator ")" line 1, position 75
Keyword "throws" line 1, position 77
Identifier "Throwable" line 1, position 84
Separator "{" line 1, position 94
Keyword "super" line 1, position 96
Separator "(" line 1, position 101
Identifier "klass" line 1, position 102
Separator ")" line 1, position 107
Separator ";" line 1, position 108
Separator "}" line 1, position 110
Separator "}" line 1, position 112
