Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "GroupTapNodePartitioner" line 1, position 14
Keyword "extends" line 1, position 38
Identifier "ExpressionRulePartitioner" line 1, position 46
Separator "{" line 1, position 72
Modifier "public" line 1, position 74
Identifier "GroupTapNodePartitioner" line 1, position 81
Separator "(" line 1, position 104
Separator ")" line 1, position 105
Separator "{" line 1, position 107
Keyword "super" line 1, position 109
Separator "(" line 1, position 114
Identifier "PartitionNodes" line 1, position 116
Separator "," line 1, position 130
Keyword "new" line 1, position 132
Identifier "GroupTapPartitionExpression" line 1, position 136
Separator "(" line 1, position 163
Separator ")" line 1, position 164
Separator ")" line 1, position 166
Separator ";" line 1, position 167
Separator "}" line 1, position 169
Separator "}" line 1, position 171
