Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "Blort" line 1, position 14
Separator "{" line 1, position 20
Modifier "static" line 1, position 22
Modifier "public" line 1, position 29
BasicType "int" line 1, position 36
Identifier "hello" line 1, position 40
Separator "(" line 1, position 45
Separator ")" line 1, position 46
Separator "{" line 1, position 48
Keyword "return" line 1, position 50
DecimalInteger "10" line 1, position 57
Separator ";" line 1, position 59
Separator "}" line 1, position 61
Modifier "static" line 1, position 63
Modifier "public" line 1, position 70
Keyword "void" line 1, position 77
Identifier "ouch" line 1, position 82
Separator "(" line 1, position 86
Separator ")" line 1, position 87
Separator "{" line 1, position 89
Identifier "hello" line 1, position 91
Separator "(" line 1, position 96
Separator ")" line 1, position 97
Separator ";" line 1, position 98
Identifier "hello" line 1, position 100
Separator "(" line 1, position 105
Separator ")" line 1, position 106
Separator ";" line 1, position 107
Separator "}" line 1, position 109
Separator "}" line 1, position 111
