Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "TapGroupTapPartitionExpression" line 1, position 14
Keyword "extends" line 1, position 45
Identifier "RuleExpression" line 1, position 53
Separator "{" line 1, position 68
Modifier "public" line 1, position 70
Identifier "TapGroupTapPartitionExpression" line 1, position 77
Separator "(" line 1, position 107
Separator ")" line 1, position 108
Separator "{" line 1, position 110
Keyword "super" line 1, position 112
Separator "(" line 1, position 117
Keyword "new" line 1, position 119
Identifier "NoGroupTapExpressionGraph" line 1, position 123
Separator "(" line 1, position 148
Separator ")" line 1, position 149
Separator "," line 1, position 150
Keyword "new" line 1, position 152
Identifier "TapGroupTapExpressionGraph" line 1, position 156
Separator "(" line 1, position 182
Separator ")" line 1, position 183
Separator ")" line 1, position 185
Separator ";" line 1, position 186
Separator "}" line 1, position 188
Separator "}" line 1, position 190
