Modifier "public" line 1, position 1
Keyword "class" line 1, position 8
Identifier "JoinEdgesSameSourceScopeExpression" line 1, position 14
Keyword "extends" line 1, position 49
Identifier "ScopeExpression" line 1, position 57
Separator "{" line 1, position 73
Modifier "public" line 1, position 75
Modifier "static" line 1, position 82
Modifier "final" line 1, position 89
Identifier "JoinEdgesSameSourceScopeExpression" line 1, position 95
Identifier "ALL_SAME_SOURCE" line 1, position 130
Operator "=" line 1, position 146
Keyword "new" line 1, position 148
Identifier "JoinEdgesSameSourceScopeExpression" line 1, position 152
Separator "(" line 1, position 186
Separator ")" line 1, position 187
Separator ";" line 1, position 188
Modifier "public" line 1, position 190
Identifier "JoinEdgesSameSourceScopeExpression" line 1, position 197
Separator "(" line 1, position 231
Separator ")" line 1, position 232
Separator "{" line 1, position 234
Separator "}" line 1, position 236
Annotation "@" line 1, position 238
Identifier "Override" line 1, position 239
Modifier "public" line 1, position 248
BasicType "boolean" line 1, position 255
Identifier "applies" line 1, position 263
Separator "(" line 1, position 270
Identifier "PlannerContext" line 1, position 272
Identifier "plannerContext" line 1, position 287
Separator "," line 1, position 301
Identifier "ElementGraph" line 1, position 303
Identifier "elementGraph" line 1, position 316
Separator "," line 1, position 328
Identifier "Scope" line 1, position 330
Identifier "scope" line 1, position 336
Separator ")" line 1, position 342
Separator "{" line 1, position 344
Identifier "FlowElement" line 1, position 346
Identifier "edgeSource" line 1, position 358
Operator "=" line 1, position 369
Identifier "elementGraph" line 1, position 371
Separator "." line 1, position 383
Identifier "getEdgeSource" line 1, position 384
Separator "(" line 1, position 397
Identifier "scope" line 1, position 399
Separator ")" line 1, position 405
Separator ";" line 1, position 406
Identifier "FlowElement" line 1, position 408
Identifier "edgeTarget" line 1, position 420
Operator "=" line 1, position 431
Identifier "elementGraph" line 1, position 433
Separator "." line 1, position 445
Identifier "getEdgeTarget" line 1, position 446
Separator "(" line 1, position 459
Identifier "scope" line 1, position 461
Separator ")" line 1, position 467
Separator ";" line 1, position 468
Identifier "Set" line 1, position 470
Operator "<" line 1, position 473
Identifier "Scope" line 1, position 474
Operator ">" line 1, position 479
Identifier "allEdgesBetween" line 1, position 481
Operator "=" line 1, position 497
Identifier "elementGraph" line 1, position 499
Separator "." line 1, position 511
Identifier "getAllEdges" line 1, position 512
Separator "(" line 1, position 523
Identifier "edgeSource" line 1, position 525
Separator "," line 1, position 535
Identifier "edgeTarget" line 1, position 537
Separator ")" line 1, position 548
Separator ";" line 1, position 549
Keyword "if" line 1, position 551
Separator "(" line 1, position 553
Identifier "allEdgesBetween" line 1, position 555
Separator "." line 1, position 570
Identifier "size" line 1, position 571
Separator "(" line 1, position 575
Separator ")" line 1, position 576
Operator "==" line 1, position 578
DecimalInteger "1" line 1, position 581
Separator ")" line 1, position 583
Keyword "return" line 1, position 585
Boolean "false" line 1, position 592
Separator ";" line 1, position 597
Keyword "return" line 1, position 599
Identifier "allEdgesBetween" line 1, position 606
Separator "." line 1, position 621
Identifier "equals" line 1, position 622
Separator "(" line 1, position 628
Identifier "elementGraph" line 1, position 630
Separator "." line 1, position 642
Identifier "incomingEdgesOf" line 1, position 643
Separator "(" line 1, position 658
Identifier "edgeTarget" line 1, position 660
Separator ")" line 1, position 671
Separator ")" line 1, position 673
Separator ";" line 1, position 674
Separator "}" line 1, position 676
Separator "}" line 1, position 678
